services:
# infrastructure

  configserver:
    image: "ghcr.io/mazaadak/config-server:latest"
    container_name: configserver
    ports:
      - "18071:18071"
    healthcheck:
      test: "curl --fail --silent localhost:18071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MAZADAK_GITHUB_TOKEN: ${MAZADAK_GITHUB_TOKEN}
    extends:
      file: common-config.yml
      service: service-base-config

  eurekaserver:
    image: "ghcr.io/mazaadak/eureka-server:latest"
    container_name: eurekaserver
    ports:
      - "18050:18050"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:18050/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: config-server-config

  mazadak-gateway:
    image: "ghcr.io/mazaadak/mazadak-gateway:latest"
#    image: "hasalism/gateway"
    container_name: mazadak-gateway
    ports:
      - "18090:18090"
    depends_on:
      redis-rate-limiter:
        condition: service_healthy
    environment:
      SPRING_DATA_REDIS_CONNECT_TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis-rate-limiter
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: common-config.yml
      service: eureka-config

  broker:
    image: apache/kafka-native:4.0.1-rc2
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    extends:
      file: common-config.yml
      service: network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 18098:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
    depends_on:
      broker:
        condition: service_started
    extends:
      file: common-config.yml
      service: network

  temporal:
    image: temporalio/auto-setup
    ports:
      - "7233:7233"
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: postgres
    depends_on:
      - postgres
    extends:
      file: common-config.yml
      service: network

  postgres:
    image: postgres:15.14-alpine3.21
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
    ports:
      - "5432:5432"
    extends:
      file: common-config.yml
      service: network

  temporal-ui:
    image: temporalio/ui:latest
    ports:
      - "8088:8080"
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    depends_on:
      - temporal
    extends:
      file: common-config.yml
      service: network

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - 1080:1080
      - 1025:1025
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \"require('net').connect(1080, '127.0.0.1').on('connect', () => process.exit(0)).on('error', () => process.exit(1))\""
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    extends:
      file: common-config.yml
      service: network

  redis-rate-limiter:
    image: redis:7-alpine
    container_name: redis-rate-limiter
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    extends:
      file: common-config.yml
      service: network

  stripe-webhook:
    image: stripe/stripe-cli
    container_name: stripe-webhook
    command:
      - "listen"
      - "--api-key"
      - "${STRIPE_SECRET_KEY}"
      - "--forward-to"
      - "http://payment-service:18081/api/payments/stripe-webhook"
    depends_on:
      - payment-service
    extends:
      file: common-config.yml
      service: network

# observability
#  minio:
#    image: minio/minio
#    entrypoint:
#      - sh
#      - -euc
#      - |
#        mkdir -p /data/loki-data && \
#        mkdir -p /data/loki-ruler && \
#        minio server /data
#    environment:
#      - MINIO_ROOT_USER=loki
#      - MINIO_ROOT_PASSWORD=supersecret
#      - MINIO_PROMETHEUS_AUTH_TYPE=public
#      - MINIO_UPDATE=off
#    ports:
#      - 9000
#    volumes:
#      - ./.data/minio:/data
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
#      interval: 15s
#      timeout: 20s
#      retries: 5
#      start_period: 30s
#    extends:
#      file: common-config.yml
#      service: network
#
#  read:
#    image: grafana/loki:latest
#    command: "-config.file=/etc/loki/config.yaml -target=read"
#    ports:
#      - 3101:3100
#      - 7946
#      - 9095
#    volumes:
#      - ./observability/loki/loki-config.yaml:/etc/loki/config.yaml
#    depends_on:
#      minio:
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 20s
#    networks: &loki-dns
#      mazadak:
#        aliases:
#          - loki
#
#  write:
#    image: grafana/loki:latest
#    command: "-config.file=/etc/loki/config.yaml -target=write"
#    ports:
#      - 3102:3100
#      - 7946
#      - 9095
#    volumes:
#      - ./observability/loki/loki-config.yaml:/etc/loki/config.yaml
#    healthcheck:
#      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 20s
#    depends_on:
#      minio:
#        condition: service_healthy
#    networks:
#      <<: *loki-dns
#
#  gateway:
#    image: nginx:latest
#    depends_on:
#      read:
#        condition: service_healthy
#      write:
#        condition: service_healthy
#    entrypoint:
#      - sh
#      - -euc
#      - |
#        cat <<EOF > /etc/nginx/nginx.conf
#        user  nginx;
#        worker_processes  5;  ## Default: 1
#
#        events {
#          worker_connections   1000;
#        }
#
#        http {
#          resolver 127.0.0.11;
#
#          server {
#            listen             3100;
#
#            location = / {
#              return 200 'OK';
#              auth_basic off;
#            }
#
#            location = /api/prom/push {
#              proxy_pass       http://write:3100\$$request_uri;
#            }
#
#            location = /api/prom/tail {
#              proxy_pass       http://read:3100\$$request_uri;
#              proxy_set_header Upgrade \$$http_upgrade;
#              proxy_set_header Connection "upgrade";
#            }
#
#            location ~ /api/prom/.* {
#              proxy_pass       http://read:3100\$$request_uri;
#            }
#
#            location = /loki/api/v1/push {
#              proxy_pass       http://write:3100\$$request_uri;
#            }
#
#            location = /loki/api/v1/tail {
#              proxy_pass       http://read:3100\$$request_uri;
#              proxy_set_header Upgrade \$$http_upgrade;
#              proxy_set_header Connection "upgrade";
#            }
#
#            location ~ /loki/api/.* {
#              proxy_pass       http://read:3100\$$request_uri;
#            }
#          }
#        }
#        EOF
#        /docker-entrypoint.sh nginx -g "daemon off;"
#    ports:
#      - "3100:3100"
#    healthcheck:
#      test: ["CMD-SHELL", "nginx -t || exit 1"]
#      interval: 15s
#      timeout: 5s
#      retries: 3
#      start_period: 5s
#    extends:
#      file: common-config.yml
#      service: network
#
#  backend:
#    image: grafana/loki:latest
#    volumes:
#      - ./observability/loki/loki-config.yaml:/etc/loki/config.yaml
#    ports:
#      - "3100"
#      - "7946"
#    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
#    depends_on:
#      gateway:
#        condition: service_healthy
#      minio:
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3100/ready"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#      start_period: 40s # <-- Crucially, increase the start period
#    extends:
#      file: common-config.yml
#      service: network
#
#  tempo:
#    image: grafana/tempo
#    container_name: tempo
#    command: -config.file /etc/tempo-config.yml
#    ports:
#      - "3110:3100"
#      - "4317:4318"
#    volumes:
#      - ./observability/tempo/tempo.yml:/etc/tempo-config.yml
#    healthcheck:
#      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 20s
#    extends:
#      file: common-config.yml
#      service: network
#
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    ports:
#      - "9098:9090"
#    volumes:
#      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    healthcheck:
#      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#    extends:
#      file: common-config.yml
#      service: network
#
#  alloy:
#    image: grafana/alloy:latest
#    volumes:
#      - ./observability/alloy/alloy-local-config.yaml:/etc/alloy/config.alloy:ro
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
#    ports:
#      - 12345:12345
#    depends_on:
#      gateway:
#        condition: service_started
#      tempo:
#        condition: service_healthy
#      prometheus:
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:12345/ready || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 60s
#    extends:
#      file: common-config.yml
#      service: network
#
#  grafana:
#    image: grafana/grafana:latest
#    environment:
#      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    depends_on:
#      gateway:
#        condition: service_healthy
#      tempo:
#        condition: service_healthy
#      prometheus:
#        condition: service_healthy
#      alloy:
#        condition: service_healthy
#    entrypoint:
#      - sh
#      - -euc
#      - |
#        /run.sh
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
#    healthcheck:
#      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 60s
#    extends:
#      file: common-config.yml
#      service: network

# services
  product-catalog-service:
    image: ghcr.io/mazaadak/product-catalog
#    image: hasalism/product-catalog:v1
#    image: mazaadak/product-catalog:v1
    container_name: product-catalog-service
    ports:
      - 18086:18086
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/productdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    extends:
      file: common-config.yml
      service: eureka-config

  auction-service:
    image: ghcr.io/mazaadak/mazadak-auctions
#    image: hasalism/auctions:v1
#    image: mazaadak/auctions:v1
    container_name: auctions-service
    ports:
      - 18089:18089
    environment:
#      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: true
      "SPRING_DATASOURCE_URL": jdbc:postgresql://auction-db:5432/auctiondb
      "SPRING_DATASOURCE_USERNAME": postgres
      "SPRING_DATASOURCE_PASSWORD": postgres
      "SPRING_DATASOURCE_DRIVER-CLASS-NAME": org.postgresql.Driver
    extends:
      file: common-config.yml
      service: eureka-config

  inventory-service:
    image: ghcr.io/mazaadak/mazadak-inventory-service
#    image: hasalism/inventory-service:v1
    container_name: inventory-service
    ports:
      - 18085:18085
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventory_db
    depends_on:
      inventory-db:
        condition: service_started
    extends:
      file: common-config.yml
      service: eureka-config

  cart-service:
    image: ghcr.io/mazaadak/mazadak-cart-service
#    image: mazaadak/cart-service:v1
    container_name: cart-service
    ports:
      - 18087:18087
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cart-db:5432/cartdb
    depends_on:
      inventory-db:
        condition: service_started
    extends:
      file: common-config.yml
      service: eureka-config

  user-service:
#    image: hasalism/user-service:v1
#    image: mazaadak/user-service:v1
    image: ghcr.io/mazaadak/user-service
    container_name: user-service
    ports:
      - 18180:18180
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/postgres
    depends_on:
      user-db:
        condition: service_started
    extends:
      file: common-config.yml
      service: eureka-config

  payment-service:
    image: ghcr.io/mazaadak/payment-service
#    image: mazaadak/payment-service:v1
    container_name: payment-service
    ports:
      - 18081:18081
    environment:
      "SPRING_DATASOURCE_URL": jdbc:postgresql://payment-db:5432/paymentdb
      "SPRING_DATASOURCE_USERNAME": postgres
      "SPRING_DATASOURCE_PASSWORD": postgres
      "SPRING_DATASOURCE_DRIVER-CLASS-NAME": org.postgresql.Driver
    extends:
      file: common-config.yml
      service: eureka-config

  order-service:
    image: ghcr.io/mazaadak/mazadak-orders
#    image: hasalism/orders:v1
#    image: mazaadak/orders:v1
    container_name: order-service
    ports:
      - 18088:18088
    environment:
      TEMPORAL_ADDRESS: temporal:7233
#      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: true
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    extends:
      file: common-config.yml
      service: eureka-config

  notifications-service:
#    image: hasalism/notifications-service:v1
#    image: mazaadak/notifications-service:v1
    image: ghcr.io/mazaadak/mazadak-notifications
    container_name: notifications
    ports:
      - 18084:18084
    depends_on:
      maildev:
        condition: service_healthy
    environment:
      MAILDEV_HOST: maildev
      SPRING_MAIL_PORT: 1025
    extends:
      file: common-config.yml
      service: eureka-config

# databases
  inventory-db:
    image: postgres:15.14-alpine3.21
    container_name: inventory-db
    ports:
      - 15439:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    extends:
      file: common-config.yml
      service: network

  cart-db:
    image: postgres:15.14-alpine3.21
    container_name: cart-db
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cartdb
    extends:
      file: common-config.yml
      service: network

  user-db:
    image: postgres:15.14-alpine3.21
    container_name: user-db
    ports:
      - 5452:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    extends:
      file: common-config.yml
      service: network

  payment-db:
    image: postgres:15.14-alpine3.21
    container_name: payment-db
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentdb
    extends:
      file: common-config.yml
      service: network

  auction-db:
    image: postgres:15.14-alpine3.21
    container_name: auction-db
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auctiondb
    extends:
      file: common-config.yml
      service: network

  product-db:
    image: postgres:15.14-alpine3.21
    container_name: product-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    extends:
      file: common-config.yml
      service: network

  order-db:
    image: postgres:15.14-alpine3.21
    container_name: order-db
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    extends:
      file: common-config.yml
      service: network

networks:
  mazadak:
    driver: "bridge"