services:
# infrastructure

  configserver:
    image: "ghcr.io/mazaadak/config-server:latest"
    container_name: configserver
    ports:
      - "18071:18071"
    healthcheck:
      test: "curl --fail --silent localhost:18071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MAZADAK_GITHUB_TOKEN: ${MAZADAK_GITHUB_TOKEN}
    extends:
      file: common-config.yml
      service: service-base-config

  eurekaserver:
    image: "ghcr.io/mazaadak/eureka-server:latest"
    container_name: eurekaserver
    ports:
      - "18050:18050"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:18050/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: config-server-config

  mazadak-gateway:
    image: "ghcr.io/mazaadak/mazadak-gateway:latest"
#    image: "hasalism/gateway:v1"
    container_name: mazadak-gateway
    ports:
      - "18090:18090"
    extends:
      file: common-config.yml
      service: eureka-config

  broker:
    image: apache/kafka-native:4.0.1-rc2
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    extends:
      file: common-config.yml
      service: network

  temporal:
    image: temporalio/auto-setup
    ports:
      - "7233:7233"
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15.14-alpine3.21
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
    ports:
      - "5432:5432"

  temporal-ui:
    image: temporalio/ui:latest
    ports:
      - "8088:8080"
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    depends_on:
      - temporal

# observability

# services
  product-catalog-service:
    image: ghcr.io/mazaadak/product-catalog
#    image: hasalism/product-catalog:v1
    container_name: product-catalog-service
    ports:
      - 18086:18086
    extends:
      file: common-config.yml
      service: eureka-config

  auction-service:
    image: ghcr.io/mazaadak/mazadak-auctions
    container_name: auctions-service
    ports:
      - 18089:18089
    extends:
      file: common-config.yml
      service: eureka-config

  inventory-service:
    image: ghcr.io/mazaadak/mazadak-inventory-service
    container_name: inventory-service
    ports:
      - 18085:18085
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventory_db
    depends_on:
      inventory-db:
        condition: service_started
    extends:
      file: common-config.yml
      service: eureka-config

  cart-service:
    image: ghcr.io/mazaadak/mazadak-cart-service
    container_name: cart-service
    ports:
      - 18087:18087
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cart-db:5432/cartdb
    depends_on:
      inventory-db:
        condition: service_started
    extends:
      file: common-config.yml
      service: eureka-config

  user-service:
#    image: hasalism/user-service:v1
    image: ghcr.io/mazaadak/user-service
    container_name: user-service
    ports:
      - 18180:18180
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/postgres
    depends_on:
      user-db:
        condition: service_started
    extends:
      file: common-config.yml
      service: eureka-config

  payment-service:
    image: ghcr.io/mazaadak/payment-service
    container_name: payment-service
    ports:
      - 18081:18081
    extends:
      file: common-config.yml
      service: eureka-config

  order-service:
    image: ghcr.io/mazaadak/mazadak-orders
    container_name: order-service
    ports:
      - 18088:18088
    depends_on:
      temporal:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: eureka-config

# databases
  inventory-db:
    image: postgres:15.14-alpine3.21
    container_name: inventory-db
    ports:
      - 15439:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    extends:
      file: common-config.yml
      service: network

  cart-db:
    image: postgres:15.14-alpine3.21
    container_name: cart-db
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cartdb
    extends:
      file: common-config.yml
      service: network

  user-db:
    image: postgres:15.14-alpine3.21
    container_name: user-db
    ports:
      - 5452:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    extends:
      file: common-config.yml
      service: network



networks:
  mazadak:
    driver: "bridge"