global:
  scrape_interval: 5s
  evaluation_interval: 5s


scrape_configs:
  - job_name: 'product-catalog'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-catalog-service:18086']
  - job_name: 'auction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auction-service:18089']
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:18085']
  - job_name: 'cart-service:'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cart-service:18087' ]
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'user-service:18180' ]
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'payment-service:18081' ]
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'order-service:18088' ]
  - job_name: 'notifications-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'notifications-service:18084' ]
  - job_name: 'mazadak-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mazadak-gateway:18090']
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eurekaserver:18050']
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['configserver:18071']